#!/usr/bin/env python3
"""Extracts MediaPipe's face-mesh connection lists from the vendored
tasks-vision bundle into a C++ header for the landmark overlay.

    python scripts/generate_face_connections.py

Reads src/assets/mediapipe/vision_bundle.mjs and writes
app/ui/face_connections.h.
"""
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
BUNDLE = ROOT / "src/assets/mediapipe/vision_bundle.mjs"
OUTPUT = ROOT / "app/ui/face_connections.h"

NAMES = [
    "TESSELATION", "FACE_OVAL", "LIPS",
    "LEFT_EYE", "LEFT_EYEBROW", "LEFT_IRIS",
    "RIGHT_EYE", "RIGHT_EYEBROW", "RIGHT_IRIS",
]


def extract(source: str, name: str) -> list[tuple[int, int]]:
    match = re.search(r"FACE_LANDMARKS_" + name + r"=\[((?:\{start:\d+,end:\d+\},?)+)\]", source)
    if not match:
        raise SystemExit(f"FACE_LANDMARKS_{name} not found in {BUNDLE}")
    return [(int(a), int(b)) for a, b in re.findall(r"\{start:(\d+),end:(\d+)\}", match.group(1))]


def main() -> None:
    source = BUNDLE.read_text(encoding="utf-8")
    lines = [
        "// Generated by scripts/generate_face_connections.py from the vendored",
        "// MediaPipe tasks-vision bundle. Do not edit.",
        "#pragma once",
        "",
        "#include <array>",
        "#include <cstdint>",
        "",
        "namespace game_face::face_connections {",
        "",
        "struct Edge {",
        "    std::uint16_t start;",
        "    std::uint16_t end;",
        "};",
    ]
    for name in NAMES:
        edges = extract(source, name)
        body = ", ".join(f"{{{a}, {b}}}" for a, b in edges)
        lines += ["", f"inline constexpr std::array<Edge, {len(edges)}> k{to_camel(name)} = {{{{", f"    {body}", "}};"]
    lines += ["", "} // namespace game_face::face_connections", ""]
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")


def to_camel(name: str) -> str:
    return "".join(part.capitalize() for part in name.split("_"))


if __name__ == "__main__":
    main()
